clock: Set window hint to GDK_WINDOW_TYPE_HINT_MENU
mate-desktop/mate-panel pull request #1164
Opened 2020-11-24 20:23 UTC by knatsakis

This makes the window appear properly when using [i3](https://i3wm.org/l) WM.

Without this patch, the clock window appears as a dock/panel window covering the full width of the screen:
![2020-11-24-221653_7680x2160_scrot](https://user-images.githubusercontent.com/5933427/100146844-3180be80-2ea3-11eb-8b09-d0726b16758d.png)

According to these [docs](http://gtk.php.net/manual/en/html/gdk/gdk.enum.windowtypehint.html) a GDK_WINDOW_TYPE_HINT_MENU is more appropriate, as the current GDK_WINDOW_TYPE_HINT_DOCK is reserved for dock/panel windows.

2020-11-24 22:52 UTC, raveit65 commented
Does the window stays open with this PR?

2020-11-25 10:35 UTC, knatsakis commented
> Does the window stays open with this PR?

Yes

2020-11-25 10:55 UTC, raveit65 commented
I expect a little bit more info than a minimalistic `yes`, before i spend more spare time on this PR.
Doesn't this break actual behaviour?
1. first click on panel-button opens the calendar window, and it is in the foreground above other windows.
2. second click on panel-button closes the calendar window.

This is useful to work in other application where you need calendar informations, eg. text-editors/writers.

2020-11-25 20:22 UTC, knatsakis commented
Hey, sorry, I didn't realize you wanted more information :-). My apologies!

> Doesn't this break actual behaviour?
> 
> 1. first click on panel-button opens the calendar window, and it is in the foreground above other windows.
> 2. second click on panel-button closes the calendar window.

No, not as far as I can tell. It continues working as you describe in 1. and 2. I have tested it with Marco and i3wm.

> This is useful to work in other application where you need calendar informations, eg. text-editors/writers.

I agree.

Let me know if you want me to provide more details or anything else!

2020-12-01 14:27 UTC, rbuj requested changes
The CalendarWindow is a panel window, so the current value is correct. There is no need to apply the change you proposed in your pull request. You should also keep in mind that window managers may have differences in the implementation of the desktop metaphor.

https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#GdkWindowTypeHint

2020-12-01 20:34 UTC, knatsakis commented
> The CalendarWindow is a panel window, so the current value is correct. There is no need to apply the change you proposed in your pull request. You should also keep in mind that window managers may have differences in the implementation of the desktop metaphor.

I was of the impression that dock/panel windows are windows that can only be placed on a screen edge and reduce the available desktop area (e.g: the main mate-panel window). I don't see how a drop-down window like the calendar window fits this description.

2020-12-01 20:43 UTC, rbuj commented
The i3 window manager handles floating windows in another way.

2020-12-01 20:43 UTC, closed without merging

2020-12-01 20:49 UTC, muktupavels commented
Calendar is not panel, is it? Or in case you think differently... Do preference window (or any other window created by panel) also has dock hint?

2020-12-01 21:00 UTC, rbuj commented
I just saw an initialization of CalendarWindow:
```
applets/clock/clock.c:805:        window = calendar_window_new (&cd->current_time,
```

2020-12-01 21:30 UTC, rbuj commented
Does GDK_WINDOW_TYPE_HINT_DOCK exclude popup windows? in such case, why isn't GDK_WINDOW_TYPE_HINT_POPUP_MENU a better approach?

2020-12-01 21:40 UTC, rbuj commented
Anyway, it's not a tear-off menu.

2020-12-09 22:56 UTC, raveit65 commented
I tested both mentioned options and they are working for me with marco WM under x11.
Sadly they do not improve the situation under wayland. Here the calendar window is always detached from panel and opens in the middle of the screen.

2020-12-11 16:38 UTC, vkareh commented
With `GDK_WINDOW_TYPE_HINT_MENU` I can now drag the calendar window anywhere on my screen. Not good.

The only ones with prevent the window from being moved are:
* `GDK_WINDOW_TYPE_HINT_DOCK` reserved for docks and panels (?)
* `GDK_WINDOW_TYPE_HINT_SPLASHSCREEN` not appropriate, but seems to work
* `GDK_WINDOW_TYPE_HINT_DESKTOP` - shows up under all windows, not really appropriate anyway

I think either `GDK_WINDOW_TYPE_HINT_UTILITY` or `GDK_WINDOW_TYPE_HINT_POPUP_MENU` would be a more appropriate choice, but we need to find a way to make it non-movable.

Alternatively, maybe i3 is not doing the right thing respecting the default size of the window, but it might just be that by seeing the DOCK hint, it automatically sets it as a toplevel panel...

2020-12-11 16:41 UTC, vkareh commented
From the [i3 docs](https://github.com/i3/i3/blob/next/docs/wsbar#L17-L26):
```
== dock mode

You typically want to see the same workspace bar on every workspace on a
specific screen. Also, you don’t want to place the workspace bar somewhere
in your layout by hand. This is where dock mode comes in: When a program sets
the appropriate hint (_NET_WM_WINDOW_TYPE_DOCK), it will be managed in dock
mode by i3. That means it will be placed at the bottom or top of the screen
(while other edges of the screen are possible in the NetWM standard, this is
not yet implemented in i3), it will not overlap any other window and it will be
on every workspace for the specific screen it was placed on initially.
```

2020-12-11 17:09 UTC, raveit65 commented
Confirmed, with `alt + left click` i can drag the window now.
Seems that is the reason why former gnome-panel-2.0 devs had chosen GDK_WINDOW_TYPE_HINT_DOCK.
I am pretty sure that was never changed after forking.

2020-12-12 10:52 UTC, knatsakis commented
> I think either `GDK_WINDOW_TYPE_HINT_UTILITY` or `GDK_WINDOW_TYPE_HINT_POPUP_MENU` would be a more appropriate choice, but we need to find a way to make it non-movable.

+1
This sounds like the most reasonable way to resolve this after all, to me as well.

2020-12-12 12:20 UTC, rbuj commented
In addition, marco and compiz keep `_NET_WM_WINDOW_TYPE_DOCK` on top of all other windows as the standard comments.

NetWM standard (aka Extended Window Manager Hints)
https://specifications.freedesktop.org/wm-spec/wm-spec-1.4.html