remove dead function mate_panel_applet_set_background_widget
mate-desktop/mate-panel pull request #1167
Opened 2020-12-04 11:47 UTC by mbkma

This function has an empty body, so removing it should be fine. I tested all affected applets, they works as before for me.

Should not be merged before https://github.com/mate-desktop/mate-media/pull/170 and https://github.com/mate-desktop/mate-applets/pull/555.

2020-12-05 12:14 UTC, rbuj commented
You cannot remove this obsolete/deprecated function from the library as there may be other components that use it, for this reason I recommend that you only remove the calls to the function and leave the implementation for compatibility.

If you want to remove it completely you should also increase the version of mate-panel library.
```C
mate-applets/accessx-status/src/applet.c:1688:    mate_panel_applet_set_background_widget (sapplet->applet,
mate-applets/battstat/battstat_applet.c:1066:    mate_panel_applet_set_background_widget (MATE_PANEL_APPLET (battstat->applet),
mate-applets/charpick/charpick.c:738:    mate_panel_applet_set_background_widget (applet, GTK_WIDGET (applet));
mate-applets/command/src/command.c:412:    mate_panel_applet_set_background_widget (applet, GTK_WIDGET (applet));
mate-applets/cpufreq/src/cpufreq-applet.c:181:    mate_panel_applet_set_background_widget (MATE_PANEL_APPLET (applet), GTK_WIDGET (applet));
mate-applets/drivemount/drivemount.c:187:        mate_panel_applet_set_background_widget (applet, GTK_WIDGET (applet));
mate-applets/geyes/src/geyes.c:392:	mate_panel_applet_set_background_widget (applet, GTK_WIDGET (applet));
mate-applets/mateweather/mateweather-applet.c:340:    mate_panel_applet_set_background_widget(gw_applet->applet,
mate-applets/multiload/main.c:503:    mate_panel_applet_set_background_widget (applet, GTK_WIDGET(applet));
mate-applets/netspeed/src/netspeed.c:1556:	mate_panel_applet_set_background_widget(MATE_PANEL_APPLET(applet_widget),
mate-applets/stickynotes/stickynotes_applet.c:409:	mate_panel_applet_set_background_widget (mate_panel_applet, applet->w_applet);
mate-applets/timerapplet/src/timerapplet.c:373:    mate_panel_applet_set_background_widget (MATE_PANEL_APPLET (applet_widget), GTK_WIDGET (applet_widget));
mate-applets/trashapplet/src/trashapplet.c:220:  mate_panel_applet_set_background_widget (MATE_PANEL_APPLET (applet),
mate-indicator-applet/src/applet-main.c:1050:		mate_panel_applet_set_background_widget(applet, item);
mate-indicator-applet/src/applet-main.c:1055:		mate_panel_applet_set_background_widget(applet, menubar);
mate-media/mate-volume-control/gvc-applet.c:517:        mate_panel_applet_set_background_widget (MATE_PANEL_APPLET (applet_widget), GTK_WIDGET (applet_widget));
mate-netbook/mate-window-picker-applet/applet.c:170:  mate_panel_applet_set_background_widget (MATE_PANEL_APPLET (applet), GTK_WIDGET (applet));
mate-sensors-applet/sensors-applet/sensors-applet.c:1246:    mate_panel_applet_set_background_widget(MATE_PANEL_APPLET(sensors_applet->applet), GTK_WIDGET(sensors_applet->applet));
mate-utils/mate-dictionary/src/gdict-applet.c:1125:  mate_panel_applet_set_background_widget (MATE_PANEL_APPLET (applet),
```

2020-12-05 21:59 UTC, lukefromdc requested changes
volume control, hardware sensors, trash, and cpufreq all crashed with this applied. No segfaults showed up in dmesg

2020-12-05 22:02 UTC, mbkma commented
@lukefromdc did you install https://github.com/mate-desktop/mate-media/pull/170 and https://github.com/mate-desktop/mate-applets/pull/555. They are necessary for this PR.

2020-12-05 22:04 UTC, lukefromdc commented
No I did not, I did NOT notice that this was a multi-repo change. Withdrawing my review as I don't have time to test all that now. Basic panel and the applets provided by the panel DID work

2020-12-05 22:05 UTC, lukefromdc reviewed
Making this a comment, as two other repos must be updated with this. That also suggests that after this is merged we increment version to 1.25.2 as the older applets are not compatable with this change

2020-12-05 22:08 UTC, mbkma commented
> If you want to remove it completely you should also increase the version of mate-panel library.

@rbuj Is there anything against removing it completely? If will make PRs removing it from the other applets as well.

2020-12-06 00:34 UTC, rbuj commented
Removing it completely will remove the function from the library symbols, so the applets that are already packaged will stop working, nor can they be built without modifying the code due to compilation errors. (missing symbol / undeclared method)

2020-12-06 05:27 UTC, lukefromdc commented
Do we know of anyone shipping 3ed party applets for mate-panel? A change like this would create real problems for users of these applets until the authors caught up, which would not be until after mate 1.26 came out if these authors are not paying attention to our development versions.

2020-12-06 10:41 UTC, mbkma commented
Well, no need to rush, now I only remove the function calls and keep the deprecated function to ensure compatibility.

2020-12-06 11:39 UTC, rbuj approved these changes
LGTM

2020-12-06 20:35 UTC, raveit65 commented
There are a few third-party applets from that i know.
- mate-menu from ubuntu-mate
- mate-applet-streamer https://github.com/assen-totin/mate-applet-streamer
- there was  a notification about other applets to add , see https://github.com/mate-desktop/mate-panel/issues/1165
- a little list https://wiki.mate-desktop.org/#!pages/plugins.md, but i think only the streamer applet is under active development.

We have also another applet :)   mate-sensor-applet which needs probably an update.

I think it's legit remove dead code in a development phase, but than we a need a library so-name bump. 
To inform affected developers shouldn't be a problem.

2020-12-07 06:03 UTC, lukefromdc approved these changes
This now works fine with existing applets, preserving compatability.

2020-12-11 01:10 UTC, merged