clock: Add option to show all location's local time in display
mate-desktop/mate-panel pull request #1207
Opened 2021-02-28 19:37 UTC by GreenArchon

Hi! Not sure if this is useful to enough people to warrant merging but I figured I'd check.

I have to work with multiple timezones, enough that clicking on the applet to get multiple local times was annoying... So I added an option to the clock applet to display the local time of all locations in the locations tabs of the settings.

![image](https://user-images.githubusercontent.com/5545257/109430533-dee9fd80-79cf-11eb-9bd0-898e001251af.png)

This MR:

* Adds the logic to optionally display all locations' formatted time in the task bar
* Adds a `show-all-locations` boolean in the settings schema
* Add a tickbox to enable the option in the settings
    *    ![image](https://user-images.githubusercontent.com/5545257/109431019-53be3700-79d2-11eb-9164-b2a1291bf41d.png)

I'm not familiar with how translations are supposed to be done however.

## Tests

This was developed tested on mate-panel 1.24 (apt-get source in Ubuntu 20.04) then ported to master. Patch applied almost cleanly, with the exception that the `cd->locations` list was now a singly-linked list (GSList) instead of a double-linked one (GList).

Works fine, only issue is adding locations sometimes crashes the applet, but it also does that without these changes so I think that is #1138 and not me :)

2021-02-28 19:56 UTC, lukefromdc commented
This could cause the clock applet to expand to the point it takes up the entire panel (or more) if the user has enough locations configured, and if there are three or more timezones configured, displaying them without labelling them could also be confusing. I think the panel should only show the me for the timezone the computer is currently using, with the others shown in the calendar as is the case now

2021-02-28 23:16 UTC, GreenArchon commented
Well, technically there's a 255 bytes limit :grimacing: 

I'm really fine with you not merging - I pushed this in case it'd be useful to someone else than just me and a few coworkers (and, let's be honest, to try not to have to carry my own patches...).

One last suggestion, and no is a very valid answer! - I get not feature creeping the clock. Could this be a hidden option, settable only by dconf, a bit like custom strftime specifiers appear to be right now?

2021-03-01 03:34 UTC, lukefromdc commented
I will leave that choice to the rest of the team for now

2021-03-01 07:06 UTC, zhuyaliang commented
I think it's better for the panel to display only the time of the current region, and the time of other time zones should be displayed in the calendar。
![2021-03-01 15-06-05屏幕截图](https://user-images.githubusercontent.com/36913152/109463286-afa2c180-7a9f-11eb-8148-3f0af4cf9b74.png)

2021-03-01 07:14 UTC, raveit65 commented
Yes, only the main time should be displayed in the panel.
You can't be in 3 citizens at the same time ;)

2021-03-01 10:52 UTC, rbuj commented on applets/clock/clock.c
> +                gboolean timeformat_dynamic = FALSE;
I don't understand the meaning/purpose of the variable `timeformat_dynamic`.

2021-03-01 11:02 UTC, rbuj requested changes
The clock applet should only show the current system clock on the panel.

2021-03-01 14:39 UTC, GreenArchon commented
Seeing the overall negative reactions I won't take more of your time on this. Thanks for spending the time to humor me!

2021-03-01 14:39 UTC, closed without merging