Window list: use GtkNotebook
mate-desktop/mate-panel pull request #1221
Opened 2021-04-14 14:30 UTC by mbkma

Also some code cleanup:
 - use g_settings directly instead of using stored values
 - use g_settings_bind when possible
 - set callback functions in glade when possible
 - remove other unneeded code complexity

The second commit is code formatting and tabs to spaces only. So for indentation please review the second commit.

2021-04-14 19:21 UTC, lukefromdc approved these changes
I just tested this, and everything seems to work. I don't have trouble turning previews on and off with this, I can confirm that in current master you have to restart the panel to apply changing this setting.

2021-04-21 03:10 UTC, zhuyaliang commented
The code structure looks cleaner and easier to understand。I like simple and efficient code

2021-04-21 03:11 UTC, zhuyaliang approved these changes

2021-04-24 20:29 UTC, rbuj requested changes
Please use a single commit for each change type and do not commit that encompasses different aspects. I do not recommend that you submit a formatting commit in this pull request.

2021-04-28 16:40 UTC, raveit65 commented
```
[rave@mother mate-panel]$ git checkout -b mbkma-window-list master
Zu neuem Branch 'mbkma-window-list' gewechselt
[rave@mother mate-panel]$ git pull https://github.com/mbkma/mate-panel.git window-list
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 12 (delta 10), reused 11 (delta 9), pack-reused 0
Entpacke Objekte: 100% (12/12), 6.89 KiB | 588.00 KiB/s, fertig.
Von https://github.com/mbkma/mate-panel
 * branch              window-list -> FETCH_HEAD
fatal: Vorspulen nicht möglich, breche ab.
[rave@mother mate-panel]$ 
```
:/

2021-04-28 17:22 UTC, raveit65 commented
Works fine under X and wayland.
But i think we can grayout `enable mouse-scrolling` for wayland.
This doesn't work under wayland.
@wmww ^^^^

2021-04-28 18:11 UTC, wmww commented
Yes, mouse scrolling isn't implemented on Wayland. Everything works for me.

2021-04-30 10:56 UTC, raveit65 commented
@wmww 
Actual we are building gtk-layer-shell from git in our travis CI config.
For some reasons it fails to build for fedora 34, see https://travis-ci.org/github/mate-desktop/mate-panel/jobs/768745044#L613
My idea is to use gtk-layer-shell  packages from distributions for travis CI builds, in result building is more stable.
f33 is using gtk-layer-shell-0.5.2-1.fc33
debian use libgtk-layer-shell-dev (0.5.2-1)
Do you think this is OK?

2021-04-30 11:31 UTC, raveit65 commented
@mbkma 
Any chance to grey-out mouse-scrolling for wayland like the other items in GUI ?

2021-04-30 14:02 UTC, mbkma commented
@raveit65 done :)
@rbuj I factored out an extra commit for the .ui file. I don't know how to split one commit which alters one file into several small commits.

2021-04-30 14:40 UTC, raveit65 commented
A little tutorial....
```
git rebase -i will do it.

First, start with a clean working directory: git status should show no pending modifications,
deletions, or additions.

To split apart your most recent commit, first:

$ git reset HEAD~

Now commit the pieces individually in the usual way, producing as many commits as you need.

If it was farther back in the tree, then

$ git rebase -i HEAD~3

where 3 is how many commits back it is.

If it was farther back in the tree than you want to count, then

$ git rebase -i 123abcd~

where 123abcd is the SHA1 of the commit you want to split up.

When you get the rebase edit screen, find the commit you want to break apart.
At the beginning of that line, replace pick with edit (e for short). Save the buffer and exit.
Rebase will now stop just after the commit you want to edit. Then:

$ git reset HEAD~

Commit the pieces individually in the usual way, producing as many commits as you need, then

$ git rebase --continue
```

2021-04-30 15:48 UTC, wmww commented
```
ldd: error: you do not have read permission for `/rootdir/gtk-layer-shell-build/_build/tmp-introspectxtwfueu3/GtkLayerShell-0.1'
```
Seems to be the source of the gtk-layer-shell build error. No idea what's causing that.

> My idea is to use gtk-layer-shell packages from distributions for travis CI builds, in result building is more stable.

As long as it works that's fine, and I don't imagine why it wouldn't work. mate-panel doesn't depend on the newest version AFAIK.

2021-04-30 16:41 UTC, raveit65 approved these changes
LGTM,
works fine under X and wayland.
Splitting out changes for UI files in a single commit seems enough for me.

2021-04-30 16:42 UTC, raveit65 commented
@rbuj 
Is this OK for you or do you really want more single commits?

2021-04-30 17:10 UTC, mbkma commented
@raveit65 I currently try to follow your tutorial... so single commits are (hopefully) coming ;)

2021-04-30 19:36 UTC, mbkma commented
I will make a new PR. @rbuj has a point, this PR is not very reviewer friendly :)

2021-04-30 19:36 UTC, closed without merging