Revert "Main menus: fix missing Places, System icons"
mate-desktop/mate-panel pull request #1434
Opened 2024-02-29 10:11 UTC by raveit65

- fix crashing panel with --replace option

This reverts commit 675f72ff302409dcbfb1991cf56fd09a294039bf.

First fix for https://github.com/mate-desktop/mate-panel/issues/1433

2024-02-29 18:09 UTC, lukefromdc requested changes
This was only half the problem, we also need to revert the earlier PR (rushed now and cannot find it) that first replaced GtkImageMenuItem with MateImageMenuItem.

With this, the "places" and "system" icons disappear from those menu items in the main menu at least w the compact menu

2024-02-29 19:31 UTC, raveit65 commented
Are you sure? I asked for that here https://github.com/mate-desktop/mate-panel/issues/1433#issuecomment-1970773847
I think https://github.com/mate-desktop/mate-panel/commit/ebb3a795a351ca600eb539ed2bba013a6533d749 is independent from GType issue.

2024-02-29 20:22 UTC, lukefromdc commented
It is, but keeping by itself doesn't actually USE MateImageMenuItem, thus the missing icons on the compact menu. What https://github.com/mate-desktop/mate-panel/commit/675f72ff302409dcbfb1991cf56fd09a294039bf actually did was to redefine these menu items to use our code, without it nothing is used for the icon

2024-02-29 21:48 UTC, raveit65 commented
My results are different. I only need to revert this commit to fix the crash, which you never couldn't reproduce.
In this post https://github.com/mate-desktop/mate-panel/issues/1433#issuecomment-1970664924 @cwendling did only speak about reverting this commit.
Anyway, feel free to close this PR if you think it is wrong.
As is said before, i fixed this already for fedora........so i have no rush and can wait.

2024-03-01 00:01 UTC, lukefromdc commented
The other commit is not the reason for the crash but rather the reason for the missing icons when used by itself. I am not going to close this now, because I think a proper technical fix keeping our replacement function is possible when used w the mate-desktop change. I will have to drill down into that, hopefully tonight.

2024-03-01 00:02 UTC, lukefromdc commented
Pretty sure the mission icons were ONLY in the compact menu BTW

2024-03-01 00:18 UTC, raveit65 commented
Which missing icons? I have no idea about you're talking about without a report about missing icons.
I don't see any missing icons with using https://github.com/mate-desktop/mate-panel/commit/ebb3a795a351ca600eb539ed2bba013a6533d749

2024-03-01 01:07 UTC, lukefromdc commented
Places and System menu items in compact menu below
![Missing_Icons](https://github.com/mate-desktop/mate-panel/assets/14036792/2d5cb2b6-6916-42b2-b7c9-66f57186742d)

2024-03-01 01:17 UTC, raveit65 commented
Closed, help yourself

2024-03-01 02:20 UTC, lukefromdc commented
OK, I will work on this and get it fixed right

2024-03-01 04:44 UTC, lukefromdc commented
I just found that https://github.com/mate-desktop/mate-panel/commit/675f72ff302409dcbfb1991cf56fd09a294039bf was incomplete, in panel-menu-items.h we are still using `gtk_image_menu_item` and not `mate_image_menu_item`, I am surprised this ever worked, anywhere

2024-03-01 05:48 UTC, lukefromdc commented
Reopening for further development. Plan is to pack the icons into those two menuitems within the panel code instead of relying on MateImageMenuItem, as a workaround for the fact that MateImageMenuItem is declared as "final," cannot be subclassed, and thus won't work as a replacement for GtkImageMenuItem in this particular case.

2024-03-01 06:26 UTC, lukefromdc commented
In testing, this shows the "Places" and "System" icons in the compact menu and does not crash on dragging a program icon from the compace menu to the panel. Needs a `mate-panel --replace` test vs 1.28.0 release on a system where that crashes

2024-03-01 06:27 UTC, lukefromdc approved these changes
In testing, this shows the "Places" and "System" icons in the compact menu and does not crash on dragging a program icon from the compace menu to the panel. Needs a mate-panel --replace test vs 1.28.0 release on a system where that crashes

2024-03-01 06:32 UTC, lukefromdc commented
I had to copy some code from menu.c to make this work as a strictly static (local to one file) function. This and using deprecated GtkImageMenuItem are a workaround for 1.28 since we should not change library dependencies. When we move on to the 1.29 development branch we can revert this, not declare MateImageMenuItem as final in mate-desktop, and use MateImageMenuItem in these two places where it has to be subclassed but now cannot be.

If others want, I can mark the places in panel-menu-items.c and the two places in panel-menu-items.h where we use GtkImageMenuItem as FIXME, and same for the two functions added to panel-menu-items.c to support this case.

2024-03-05 06:38 UTC, lukefromdc commented
We can close this in favor of https://github.com/mate-desktop/mate-desktop/pull/603 and a panel PR to replace GtkImageMenuItem with MateImageMenuItem and include libmate-desktop/mate-image-menu-item.h in mate-panel/panel-menu-items.h if we decide to allow a breaking change just after the brand-new 1.28 release, or we can keep this fix for 1.28, bump versions, and use those for 1.29 to avoid a breaking change in 1.28.0. Deeming this not my choice to make

2024-03-05 06:41 UTC, zhuyaliang commented
If we accept it https://github.com/mate-desktop/mate-desktop/pull/603 We can continue to use ```MATE_TYPE_IMAGE_MENU_ITEM```.No need to  reverts commit

2024-03-06 11:17 UTC, cwendling commented
As said in https://github.com/mate-desktop/mate-desktop/pull/603#issuecomment-1980629626, I don't really like how this is growing, and would rather merge https://github.com/mate-desktop/mate-desktop/pull/603 and depend on it (that is, update the dependency and use the right type as the parents in the structure).

2024-03-06 16:12 UTC, raveit65 commented
Can be closed or not?

2024-03-06 18:17 UTC, lukefromdc commented
Fine with closing this so long as we are OK with depending on a new mate-desktop version

2024-03-06 18:17 UTC, closed without merging